Repository baseball-diary/baseball-FE, pull requests merged in 2024-08, with the labels that each got.

#4 [#3] 이슈 템플릿 syntax error 해결 및 옵셔널 설정
  .github/ISSUE_TEMPLATE/feat.yml
  .github/ISSUE_TEMPLATE/fix.yml
  .github/ISSUE_TEMPLATE/style.yml
Labels: fix

#7 [#5] recoil 초기 세팅 및 eslint 수정
  .eslintrc.js
  src/screens/App.tsx
  src/stores/.gitkeep
  src/stores/userState.ts
Labels: feat, fix

#9 [#8] tanstack query 초기 세팅
  package-lock.json
  package.json
  src/screens/App.tsx
  src/utils/queryClient.ts
Labels: feat
